services:
  downsub-api:
    build: .
    container_name: downsub-api
    hostname: downsub-api
    environment:
      - DOWNSUB_CLEANUP_ENABLED=true
      - DOWNSUB_CLEANUP_AGE=300
      - RESULT_OPTION=file
    volumes:
      - ./output:/app/output
    networks:
      - downsub-api-network
    restart: unless-stopped

networks:
  downsub-api-network:
    driver: bridge

