services:
  downsub-api:
    build: .
    container_name: downsub-api
    hostname: downsub-api
    environment:
      - ENVIRONMENT=docker
      - DOWNSUB_CLEANUP_ENABLED=true
      - DOWNSUB_CLEANUP_AGE=300
      - RESULT_OPTION=file
    volumes:
      - ./output:/app/output
    networks:
      - api-aurensoft-network
    restart: unless-stopped

networks:
  api-aurensoft-network:
    external: true
